# enable truecolor support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# allow mouse mode
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set tmux prefix to C-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# notify pane focus
set -g focus-events on

# vim mode for copy mode
set -g mode-keys vi
# vim style select and yank key bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim-style splits (split in current dir)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
