# Enable truecolor support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Notify pane focus
set -g focus-events on

# Set vim mode for copy mode
set -g mode-keys vi

# vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim-style splits
bind | split-window -h
bind - split-window -v
